<h1>Posty</h1>

<div id="posts">
<?php foreach($this->posts as $post): ?>
    <div class="post">
        <h2 class="title"><a href="<?php echo $this->url(array('action' => 'show', 'controller' => 'post', 'id' => $post['id']), NULL) ?>"><?php echo $this->escape($post['title']) ?></a></h2>
        <div class="short"><?php echo $this->escape($post['short']) ?></div>
    </div>
<?php endforeach ?>
</div>
