<h1>Forum dyskusyjne</h1>

<?php foreach ($this->categories as $category): ?>
    <h2><?php echo $this->escape($category['name']) ?></h2>
    <table class="forum-category">
        <tr>
            <th class="title">Tytuł tematu</th>
            <th class="author">Autor</th>
            <th class="number_of_posts">Ilość odpowiedzi</th>
            <th class="created_at">Data utworzenia</th>
        </tr>
        <?php foreach ($this->forum_topic->findByCategory($category['id']) as $topic): ?>
        <tr>
            <td><a href="<?php echo $this->url(array('action' => 'show_topic', 'controller' => 'forum', 'category_id' => $category['id'], 'topic_id' => $topic['id']), NULL) ?>"><?php echo $this->escape($topic['title']) ?></a></td>
            <td><?php echo $this->escape($topic['name'])  ?></td>
            <td><?php echo $this->escape($topic['number_of_posts'])  ?></td>
            <td><?php echo $this->escape($topic['created_at'])  ?></td>
        </tr>
        <?php endforeach ?>
    </table>

    <?php if ($this->loggedIn): ?>
        <a href="<?php echo $this->url(array('action' => 'add_topic', 'controller' => 'forum', 'category_id' => $category['id']), NULL) ?>">Dodaj nowy temat</a>
    <?php endif ?>
<?php endforeach ?>