<h2><?php echo $this->escape($this->topic['title']) ?></h2>
Autor tematu: <span class="topic-author"><?php echo $this->escape($this->topic['name']) ?></span>

<table style="width: 100%">
    <tr>
        <th>Autor</th>
        <th>Treść wiadomości</th>
        <th>Data utworzenia</th>
    </tr>
    <tr>
        <td><?php echo $this->escape($this->topic['name']) ?></td>
        <td><?php echo $this->escape($this->topic['content']) ?></td>
        <td><?php echo $this->escape($this->topic['created_at']) ?></td>
    </tr>
<?php foreach ($this->posts as $post): ?>
    <tr>
        <td><?php echo $this->escape($post['name']) ?></td>
        <td><?php echo $this->escape($post['content']) ?></td>
        <td><?php echo $this->escape($post['created_at']) ?></td>
    </tr>
<?php endforeach ?>
</table>

<?php if ($this->loggedIn): ?>
    <?php echo $this->form ?>
<?php endif ?>