<!DOCTYPE HTML>
<html>
<head>
<title>CSS3_one</title>
<meta name="description" content="website description">
<meta name="keywords" content="website keywords, website keywords">
<meta http-equiv="content-type" content="text/html; charset=windows-1252">
<link rel="stylesheet" type="text/css" id="theme" href="/css/style.css">
<!-- modernizr enables HTML5 elements and feature detects --><script type="text/javascript" src="/js/modernizr-1.5.min.js"></script>
</head>
<body>
  <div id="main">
    <header><div id="logo">
        <div id="logo_text">
          <!-- class="logo_colour", allows you to change the colour of the text -->
          <h1><a href="/">CSS3<span class="logo_colour">_one</span></a></h1>
          <h2>Simple. Contemporary. Website Template.</h2>
        </div>
        <form method="post" action="#" id="search">
          <input class="search" type="text" name="search_field" value="search....." onclick="javascript: document.forms['search'].search_field.value=''"><input name="search" type="image" style="float: right;border: 0; margin: 20px 0 0 0;" src="/images/search.png" alt="search" title="search">
</form>
      </div>
      <nav><ul class="sf-menu" id="nav">
<li class="current"><a href="index.html">Home</a></li>
          <li><a href="examples.html">Examples</a></li>
          <li><a href="page.html">A Page</a></li>
          <li><a href="another_page.html">Another Page</a></li>
          <li>
<a href="#">Example Drop Down</a>
            <ul>
<li><a href="#">Drop Down One</a></li>
              <li>
<a href="#">Drop Down Two</a>
                <ul>
<li><a href="#">Sub Drop Down One</a></li>
                  <li><a href="#">Sub Drop Down Two</a></li>
                  <li><a href="#">Sub Drop Down Three</a></li>
                  <li><a href="#">Sub Drop Down Four</a></li>
                  <li><a href="#">Sub Drop Down Five</a></li>
                </ul>
</li>
              <li><a href="#">Drop Down Three</a></li>
              <li><a href="#">Drop Down Four</a></li>
              <li><a href="#">Drop Down Five</a></li>
            </ul>
</li>
          <li><a href="contact.php">Contact Us</a></li>
        </ul></nav></header><div id="site_content">
      <div id="sidebar_container">
        <div class="sidebar">
          <h3>Latest News</h3>
          <div class="sidebar_item">
            <!-- insert your sidebar items here -->
            <h4>New Website Launched</h4>
            <h5>January 1st, 2012</h5>
            <p>2012 sees the redesign of our website. Take a look around and let us know what you think.<br><a href="#">Read more</a></p>
          </div>
          <div class="sidebar_base"></div>
        </div>
        <div class="sidebar">
          <h3>Useful Links</h3>
          <div class="sidebar_item">
            <ul>
<li><a href="#">link 1</a></li>
              <li><a href="#">link 2</a></li>
              <li><a href="#">link 3</a></li>
              <li><a href="#">link 4</a></li>
            </ul>
</div>
          <div class="sidebar_base"></div>
        </div>
        <div class="sidebar">
          <h3>More Useful Links</h3>
          <div class="sidebar_item">
            <ul>
<li><a href="#">link 1</a></li>
              <li><a href="#">link 2</a></li>
              <li><a href="#">link 3</a></li>
              <li><a href="#">link 4</a></li>
            </ul>
</div>
          <div class="sidebar_base"></div>
        </div>
      </div>
      <?php echo $this->layout()->content; ?>
    </div>
    <footer><p><a href="index.html">Home</a> | <a href="examples.html">Examples</a> | <a href="page.html">A Page</a> | <a href="another_page.html">Another Page</a> | <a href="contact.php">Contact Us</a></p>
      <p>Copyright &copy; CSS3_one | <a href="http://www.css3templates.co.uk">design from css3templates.co.uk</a><!--%@##--> Design provided by <a href="http://www.freewebtemplates.com/">Free Website Templates</a>.<!--##@%--></p>
    </footer>
</div>
  <!-- javascript at the bottom for fast page loading -->
  <script type="text/javascript" src="js/jquery.js"></script><script type="text/javascript" src="js/jquery.easing-sooper.js"></script><script type="text/javascript" src="js/jquery.sooperfish.js"></script><script type="text/javascript">
    $(document).ready(function() {
      $('ul.sf-menu').sooperfish();
    });
  </script>
</body>
</html>
