<!DOCTYPE HTML>
<html>
<head>
<title>Blog</title>
<meta name="description" content="website description">
<meta name="keywords" content="website keywords, website keywords">
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" id="theme" href="/css/style.css">
<!-- modernizr enables HTML5 elements and feature detects --><script type="text/javascript" src="/js/modernizr-1.5.min.js"></script>
</head>
<body>
  <div id="main">
    <header><div id="logo">
        <div id="logo_text">
          <!-- class="logo_colour", allows you to change the colour of the text -->
          <h1><a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'index'), NULL, 'default') ?>">Blog</a></h1>
          <h2>Bardzo prosty blog</h2>
        </div>
      </div>
      <nav>
        <ul class="sf-menu" id="nav">
          <li class="current"><a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'index'), NULL, 'default') ?>">Strona główna</a></li>
          <li><a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'forum'), NULL, 'default') ?>">Forum</a></li>
        <?php if (!$this->loggedIn): ?>
          <li><a href="<?php echo $this->url(array('action' => 'login', 'controller' => 'user'), NULL, 'default') ?>">Logowanie</a></li>
          <li><a href="<?php echo $this->url(array('action' => 'register', 'controller' => 'user'), NULL, 'default') ?>">Rejestracja</a></li>
        <?php else: ?>
          <li><a href="<?php echo $this->url(array('action' => 'new', 'controller' => 'post'), NULL, 'default') ?>">Dodaj posta</a></li>
          <li><a href="<?php echo $this->url(array('action' => 'logout', 'controller' => 'user'), NULL, 'default') ?>">Wyloguj (<?php echo $this->userData['name'] ?>)</a></li>
        <?php endif ?>
        </ul></nav></header><div id="site_content">
      <div id="sidebar_container">
        <div class="sidebar">
          <h3>Ostatnie 5 wpisów</h3>
          <div class="sidebar_item">
            <ul>
            <?php foreach($this->new_posts as $post): ?>
              <li><a href="<?php echo $this->url(array('action' => 'show', 'controller' => 'post', 'id' => $post['id']), NULL, 'default') ?>"><?php echo $post['title'] ?></a></li>
            <?php endforeach ?>
            </ul>
          </div>
          <div class="sidebar_base"></div>
        </div>
      </div>
      <?php echo $this->layout()->content; ?>
    </div>
    <footer><p><a href="index.html">Home</a> | <a href="examples.html">Examples</a> | <a href="page.html">A Page</a> | <a href="another_page.html">Another Page</a> | <a href="contact.php">Contact Us</a></p>
      <p>Copyright &copy; CSS3_one | <a href="http://www.css3templates.co.uk">design from css3templates.co.uk</a><!--%@##--> Design provided by <a href="http://www.freewebtemplates.com/">Free Website Templates</a>.<!--##@%--></p>
    </footer>
</div>
  <!-- javascript at the bottom for fast page loading -->
  <script type="text/javascript" src="js/jquery.js"></script><script type="text/javascript" src="js/jquery.easing-sooper.js"></script><script type="text/javascript" src="js/jquery.sooperfish.js"></script><script type="text/javascript">
    $(document).ready(function() {
      $('ul.sf-menu').sooperfish();
    });
  </script>
</body>
</html>
