<form method="post">
    <table>
        <tr>
            <th>Tytuł posta</th>
            <td><input type="text" name="title" /></td>
        </tr>

        <tr>
            <th>Krótki wstęp:</th>
            <td><textarea name="short"></textarea></td>
        </tr>

        <tr>
            <th>Treść:</th>
            <td><textarea name="content"></textarea></td>
        </tr>

        <tr>
            <td colspan="2"><input type="submit" value="Zapisz" /></td>
        </tr>
    </table>
</form>