<div id="post-full">
    <h2><?php echo $this->post['title'] ?></h2>
<?php if($this->loggedIn): ?>
    <a href="<?php echo $this->url(array('action' => 'edit', 'controller' => 'post', 'id' => $this->post['id']), NULL, 'default') ?>">Edytuj</a>
<?php endif ?>
    <div class="author">Post dodał: <b><?php echo $this->post['name'] ?></b></div>
    <div class="short"><?php echo $this->post['short'] ?></div>
    <div class="content">
        <?php echo $this->post['content'] ?>

        <p></p>
        <p></p>

        <div id="comments">
            <?php foreach($this->comments as $comment): ?>
                <div class="comment">
                    <div class="title">Napisany przez: <?php if ($comment['name']): ?><b><?php echo $comment['name'] ?></b><?php else: ?><i>Nieznajomy</i><?php endif ?> dnia <?php echo $comment['date'] ?></div>

                    <div class="body"><?php echo $comment['body'] ?></div>
                </div>
            <?php endforeach ?>
        </div>

        <p></p>
        <p></p>
        <h4>Dodaj komentarz</h4>
        <div class="comments">
            <?php echo $this->form ?>
        </div>
    </div>

</div>
